version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbitmq-producer:
    build:
      context: ../rabbitmq-producer
      dockerfile: ../rabbitmq-producer/Dockerfile
    container_name: rabbitmq-producer
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    entrypoint: ["sh", "-c", "sleep 30 && java -jar app.jar"]

  rabbitmq-consumer:
    build:
      context: ../rabbitmq-consumer
      dockerfile: ../rabbitmq-consumer/Dockerfile
    container_name: rabbitmq-consumer
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    entrypoint: ["sh", "-c", "sleep 60 && java -jar app.jar"]

  rabbitmq-second-consumer:
    build:
      context: ../rabbitmq-second-consumer
      dockerfile: ../rabbitmq-second-consumer/Dockerfile
    container_name: rabbitmq-second-consumer
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    entrypoint: ["sh", "-c", "sleep 60 && java -jar app.jar"]
